#!/bin/bash
#SBATCH --job-name=cc_cpm_bigwigs
#SBATCH --output=cc_cpm_bigwigs_%j.log
#SBATCH --error=cc_cpm_bigwigs_%j.err
#SBATCH -c 8
#SBATCH --mem=60000
#SBATCH --time=12:00:00
# =============================================================================
# Fig. 3a, step 1 — CPM-normalized Calling Card bigWigs (per sex)
# =============================================================================
# Builds CPM-normalized bigWig tracks of Egr1 Calling Card transposition signal
# for male and female cells, used as the input to the panel-a heatmap
# (panel_a_2_plot_heatmap.sh) and to the browser tracks (panel b).
#
# Method: count transposition events ("hops") in 20-bp genome bins, scale each
# sample to counts-per-million (1e6 / total hops), and convert to bigWig.
#
# NOTE: raw inputs (qbeds) and the working dir live on HTCF/LTS; this script is
# committed for provenance and is run on the cluster. See panel_a_README.md.
# Tools: bedtools2, kentutils (bedGraphToBigWig) — loaded via spack below.
# =============================================================================

set -euo pipefail

# ---- paths (HTCF) -----------------------------------------------------------
WORKDIR=/scratch/rmlab/rmlab_shared3/l.llaci/Egr1_paper/cpm_bigwigs
QBED_DIR=/lts/rmlab/rmlab_shared3/l.llaci/Egr1_paper/Egr1_CC_Lori/101524_Egr1CC_analysis/output_and_analysis/insertions

# chrY-filtered Egr1 insertions, per sex
MALE_QBED=$QBED_DIR/TCGTG_Male_Egr1_22CNMGLT4_S249_L008_R1_001_map_sort_final_chrY_filtered.qbed
FEMALE_QBED=$QBED_DIR/TCGTG_Female_Egr1_22CNMGLT4_S249_L008_R1_001_map_sort_final_chrY_filtered.qbed

mkdir -p "$WORKDIR"; cd "$WORKDIR"
eval "$(spack load --sh bedtools2)"

# ---- mm10 chrom sizes + 20-bp bins (skip if present) ------------------------
[[ -f mm10.chrom.sizes ]] || \
  wget -q https://hgdownload.cse.ucsc.edu/goldenpath/mm10/bigZips/mm10.chrom.sizes
[[ -f mm10_Genome_20bp_Bins.sorted ]] || {
  bedtools makewindows -g mm10.chrom.sizes -w 20 > mm10_Genome_20bp_Bins.bed
  bedtools sort -i mm10_Genome_20bp_Bins.bed > mm10_Genome_20bp_Bins.sorted
}

# ---- per-sex: sort -> count hops/bin -> CPM scale -> bigWig ------------------
make_cpm_bw () {
  local qbed="$1" tag="$2"
  bedtools sort -i "$qbed" > "${tag}.qbed.sorted"
  bedtools annotate -counts -i mm10_Genome_20bp_Bins.sorted \
      -files "${tag}.qbed.sorted" > "${tag}.bedgraph"
  local total scale
  total=$(wc -l < "${tag}.qbed.sorted")
  scale=$(awk -v t="$total" 'BEGIN{printf "%.6f", 1000000/t}')
  echo "$tag: total hops = $total  ->  CPM scale = $scale"
  awk -v s="$scale" 'BEGIN{OFS="\t"} {print $1,$2,$3,$4*s}' \
      "${tag}.bedgraph" | bedtools sort -i - > "${tag}_CPM_sorted.bedgraph"
}

make_cpm_bw "$MALE_QBED"   Male_Egr1
make_cpm_bw "$FEMALE_QBED" Female_Egr1

eval "$(spack load --sh kentutils)"
bedGraphToBigWig Male_Egr1_CPM_sorted.bedgraph   mm10.chrom.sizes Male_Egr1_CPM.bw
bedGraphToBigWig Female_Egr1_CPM_sorted.bedgraph mm10.chrom.sizes Female_Egr1_CPM.bw

echo "Done:"
echo "  $WORKDIR/Male_Egr1_CPM.bw"
echo "  $WORKDIR/Female_Egr1_CPM.bw"

# ---- OPTIONAL: WT bigWigs + log2(Egr1/WT) enrichment ------------------------
# The paper panel a uses the raw CPM bigWigs above. A background-controlled
# log2(Egr1/WT) alternative is generated by also building Male_WT_CPM.bw /
# Female_WT_CPM.bw (same steps on the *_WT_* qbeds) then:
#   bigwigCompare -b1 Male_Egr1_CPM.bw -b2 Male_WT_CPM.bw \
#       --operation log2 --pseudocount 1 --binSize 10 -o Male_Egr1_vs_WT_log2.bw
